Add Windows documentation
scrapd/docs pull request #27
Opened 2019-08-09 00:41 UTC by lalver1

Types of changes
----------------

- Added documentation for setting up Python in Windows.
- Added documentation for setting up the developer environment in Windows.

Description
-----------

- Added Windows documentation and changed the layout of the contributor zone to separate 'learning resources' and 'developer setup'. This change seemed to make sense since the documentation started getting too long for only one section.

2019-08-23 14:03 UTC, rgreinho requested changes
Great work @lalver1! Just a little bit of simplification and rearranging the documentation and that will be perfect!

2019-08-23 14:03 UTC, rgreinho commented on docs/learning/developer.md
> +for instance `inv nox -s test`, or directly with `nox -s test`
This looks great, but there is a lot of repetition. I think it would simplify the instructions to have only one paragraph and to explain the difference to activate a venv between Windows and Linux/OSX.

2019-08-23 14:03 UTC, rgreinho commented on docs/learning/learning.md
> +
This looks great too, but per our conversation, this should have its own dedicated file as it is more a tutorial than a learning resource.

2019-08-24 05:25 UTC, lalver1 commented on docs/learning/developer.md
> +for instance `inv nox -s test`, or directly with `nox -s test`
I agree, there is a lot of repetition. I rearranged the content to reduce repeated paragraphs:
Install packages (all 3 OSs same)
Setup local env (separate for macOS&linux and Win)
Run CI tasks (all 3 OSs same)

2019-08-24 05:25 UTC, lalver1 commented on docs/learning/learning.md
> +
Yes, I created a new file for this section.

2019-08-24 14:50 UTC, rgreinho approved these changes
Love it! Great work @lalver1 !

2019-08-24 14:51 UTC, merged